import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NavbarDefault } from "@/components/container/navbar";
import { FooterDefault } from "@/components/container/footer";

const font = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font} max-w-6xl mx-auto antialiased space-y-6`}>
        <NavbarDefault />
        {children}
        <FooterDefault />
      </body>
    </html>
  );
}
